name: introML
channels:
  - pytorch
  - conda-forge
dependencies:
  - altair=5.5.0
  - anyio=4.3.0
  - appnope=0.1.4
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.18
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - blinker=1.9.0
  - blosc=1.21.6
  - boltons=24.0.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.16.0
  - cfgv=3.3.1
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - conda=24.11.3
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.2.1
  - cryptography=44.0.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.15
  - distlib=0.3.9
  - distro=1.9.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.7.0
  - filelock=3.14.0
  - fiona=1.9.5
  - fmt=10.2.1
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=2.0.0
  - frozendict=2.4.6
  - gdal=3.7.2
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gradescope-utils=0.5.0
  - h11=0.14.0
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - hypothesis=6.131.15
  - icu=73.2
  - identify=2.6.10
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.2
  - json-c=0.17
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.1
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=20.1.4
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.2
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgdal=3.7.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.24
  - libparquet=16.1.0
  - libpng=1.6.47
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.32
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.7
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - menuinst=2.0.2
  - minizip=4.0.7
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munch=4.0.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - narwhals=1.38.2
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nodeenv=1.9.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.105
  - numba=0.56.4
  - numpy=1.23.5
  - openjpeg=2.5.1
  - openssl=3.5.0
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.6.4
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.5.0
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - pre-commit=4.2.0
  - proj=9.3.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - protobuf=4.25.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydeck=0.9.1
  - pygithub=2.5.0
  - pygments=2.18.0
  - pyjwt=2.10.1
  - pynacl=1.5.0
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pytest=8.3.5
  - pytest-env=1.1.5
  - pytest-runner=6.0.0
  - python=3.10.15
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - rtree=1.2.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=69.5.1
  - shapely=2.0.2
  - six=1.16.0
  - smmap=5.0.2
  - snappy=1.2.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spdlog=1.13.0
  - sqlite=3.49.2
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - streamlit=1.45.0
  - sympy=1.12
  - tenacity=9.1.2
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tiledb=2.16.3
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.3
  - truststore=0.8.0
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.1
  - virtualenv=20.31.2
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - wordcloud=1.9.4
  - wrapt=1.17.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - albumentations==1.4.6
      - annotated-types==0.6.0
      - astroid==3.2.3
      - black==24.4.2
      - cython==3.0.10
      - dill==0.3.8
      - einops==0.8.0
      - emoji==2.12.1
      - entmax==1.3
      - fsspec==2024.3.1
      - huggingface-hub==0.23.0
      - imageio==2.34.1
      - isort==5.13.2
      - lazy-loader==0.4
      - mccabe==0.7.0
      - mypy==1.10.1
      - mypy-extensions==1.0.0
      - opencv-python-headless==4.9.0.80
      - pathspec==0.12.1
      - pix2tex==0.1.2
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pylint==3.2.5
      - pynput==1.7.6
      - pyobjc-framework-applicationservices==10.2
      - pyobjc-framework-coretext==10.2
      - pyobjc-framework-quartz==10.2
      - pyqt6==6.7.0
      - pyqt6-qt6==6.7.0
      - pyqt6-sip==13.6.0
      - pyqt6-webengine==6.7.0
      - pyqt6-webengine-qt6==6.7.0
      - pyside6==6.7.0
      - pyside6-addons==6.7.0
      - pyside6-essentials==6.7.0
      - python-dateutil==2.9.0.post0
      - regex==2024.4.28
      - safetensors==0.4.3
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - screeninfo==0.8.1
      - shiboken6==6.7.0
      - tifffile==2024.5.3
      - timm==0.5.4
      - tokenizers==0.19.1
      - tomlkit==0.13.0
      - transformers==4.40.1
      - x-transformers==0.15.0
